name: Otomatik Mail Gönderimi

on:
  schedule:
    - cron: '0 16 * * 1-5' # Türkiye saatiyle 19:00 (UTC+3 → 16:00 UTC)
  workflow_dispatch: # Manuel tetikleme için

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v4

      - name: Python ortamını kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install yfinance>=0.2.40 pandas>=2.2.2 numpy>=1.26.4 openpyxl>=3.1.5
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Secret'ları kontrol et
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          if [ -z "$EMAIL_ADDRESS" ]; then echo "HATA: EMAIL_ADDRESS eksik"; exit 1; fi
          if [ -z "$EMAIL_PASSWORD" ]; then echo "HATA: EMAIL_PASSWORD eksik"; exit 1; fi
          if [ -z "$RECIPIENT_EMAIL" ]; then echo "HATA: RECIPIENT_EMAIL eksik"; exit 1; fi
          echo "Tüm secret'lar tanımlı."

      - name: Python scriptini çalıştır
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python posta-gonder.py || echo "Script çalıştırılırken hata oluştu, hata logu kontrol edilecek."

      - name: Excel ve hata logunu artifact olarak yükle
        if: always() # Hata olsa bile çalışır
        uses: actions/upload-artifact@v4
        with:
          name: dip-tepe-tarama
          path: |
            Dip_Tepe_Tarama_Tum_Zamanlar_*.xlsx
            error_log.txt
          if-no-files-found: warn
