name: Otomatik Mail Gönderme

on:
  schedule:
    - cron: '0 16 * * 1-5' # Türkiye saatiyle 19:00 (UTC 16:00)
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Ortamını Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # Yüklü kütüphaneleri loglara yazdır

      - name: Python Betiğini Çalıştır
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python posta-gonder.py
