name: Otomatik Mail Gönderme

on:
  schedule:
    - cron: '0 19 * * 1-5' # Hafta içi her gün saat 19:00'da çalışır (UTC)

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Ortamını Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Kullanmak istediğiniz Python sürümünü seçin

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Python Betiğini Çalıştır
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python mail_gonder.py
