name: Colab Kodunu Otomatik Çalıştır

on:
  schedule:
    - cron: '0 16 * * 1-5'  # UTC saatine göre 19:00 Türkiye saati = 16:00 UTC
  workflow_dispatch:        # Elle çalıştırmak için de izin verir

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu çek
      uses: actions/checkout@v3

    - name: Python yükle
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli kütüphaneleri yükle
      run: |
        pip install -r requirements.txt || true

    - name: Python scriptini çalıştır
      run: python main.py
