name: Otomatik Mail Gönderme

on:
  schedule:
    - cron: '0 16 * * 1-5' # Türkiye saatiyle 19:00 (UTC 16:00)
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Python Ortamını Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || { echo "Bağımlılık yükleme başarısız!"; exit 1; }
          else
            echo "requirements.txt dosyası bulunamadı!"
            exit 1
          fi
          pip list

      - name: Python Betiğini Çalıştır
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          echo "Betik çalıştırılıyor: posta-gonder.py"
          python posta-gonder.py || { echo "Betik çalıştırılırken hata oluştu!"; exit 1; }
