- name: Secret'ları kontrol et
  env:
    EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
  run: |
    if [ -z "$EMAIL_ADDRESS" ]; then echo "HATA: EMAIL_ADDRESS eksik"; else echo "EMAIL_ADDRESS tanımlı"; fi
    if [ -z "$EMAIL_PASSWORD" ]; then echo "HATA: EMAIL_PASSWORD eksik"; else echo "EMAIL_PASSWORD tanımlı"; fi
    if [ -z "$RECIPIENT_EMAIL" ]; then echo "HATA: RECIPIENT_EMAIL eksik"; else echo "RECIPIENT_EMAIL tanımlı"; fi

- name: Python scriptini çalıştır
  env:
    EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
  run: python posta-gonder.py
