name: Otomatik Mail Gönderimi

on:
  schedule:
    - cron: '0 16 * * 1-5'  # UTC saatine göre: Türkiye saatiyle 19:00 (UTC+3 → 16:00)
  workflow_dispatch:        # Elle tetiklemek için

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: pip install -r requirements.txt

    - name: Python scripti çalıştır
      run: python posta-gonder.py
